/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Coordinates = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
});
export const ModifierInstance = IDL.Record({
  'modifierInstanceId' : IDL.Nat,
  'modifierType' : IDL.Text,
  'model_url' : IDL.Text,
  'rarity_tier' : IDL.Nat,
  'multiplier_value' : IDL.Float64,
});
export const LandData = IDL.Record({
  'decorationURL' : IDL.Opt(IDL.Text),
  'baseTokenMultiplier' : IDL.Float64,
  'lastChargeUpdate' : Time,
  'upgradeLevel' : IDL.Nat,
  'principal' : IDL.Principal,
  'landId' : IDL.Nat,
  'lastClaimTime' : Time,
  'biome' : IDL.Text,
  'chargeCap' : IDL.Nat,
  'cycleCharge' : IDL.Int,
  'plotName' : IDL.Text,
  'coordinates' : Coordinates,
  'attachedModifications' : IDL.Vec(ModifierInstance),
});
export const Modifier = IDL.Record({
  'name' : IDL.Text,
  'asset_url' : IDL.Text,
  'mod_id' : IDL.Nat,
  'rarity_tier' : IDL.Nat,
  'multiplier_value' : IDL.Float64,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Result_4 = IDL.Variant({ 'ok' : LandData, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClaimResult = IDL.Variant({
  'success' : IDL.Record({
    'tokensClaimed' : IDL.Nat,
    'newBalance' : IDL.Nat,
    'nextClaimTime' : IDL.Int,
  }),
  'mintFailed' : IDL.Text,
  'cooldown' : IDL.Record({
    'currentBalance' : IDL.Nat,
    'remainingTime' : IDL.Int,
  }),
  'insufficientCharge' : IDL.Record({
    'required' : IDL.Nat,
    'current' : IDL.Int,
  }),
});
export const LootCache = IDL.Record({
  'owner' : IDL.Principal,
  'tier' : IDL.Nat,
  'cache_id' : IDL.Nat,
  'discovered_at' : Time,
  'is_opened' : IDL.Bool,
});
export const Result_3 = IDL.Variant({ 'ok' : LootCache, 'err' : IDL.Text });
export const Result_2 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TopLandEntry = IDL.Record({
  'upgradeLevel' : IDL.Nat,
  'principal' : IDL.Principal,
  'tokenBalance' : IDL.Nat,
  'plotName' : IDL.Text,
});
export const Result_1 = IDL.Variant({
  'ok' : ModifierInstance,
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpgradeResult = IDL.Variant({
  'maxLevelReached' : IDL.Null,
  'success' : IDL.Record({ 'newLevel' : IDL.Nat, 'remainingTokens' : IDL.Nat }),
  'insufficientTokens' : IDL.Record({
    'required' : IDL.Nat,
    'current' : IDL.Nat,
  }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetLandData' : IDL.Func([IDL.Nat], [IDL.Opt(LandData)], []),
  'adminSetAllModifiers' : IDL.Func([IDL.Vec(Modifier)], [Result], []),
  'applyModifier' : IDL.Func([IDL.Nat, IDL.Nat], [Result_4], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimRewards' : IDL.Func([IDL.Nat], [ClaimResult], []),
  'discoverLootCache' : IDL.Func([IDL.Nat], [Result_3], []),
  'getAllModifiers' : IDL.Func([], [IDL.Vec(Modifier)], ['query']),
  'getAssetCanisterCycleBalance' : IDL.Func([], [Result_2], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentCbrBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getLandData' : IDL.Func([], [IDL.Vec(LandData)], []),
  'getLandDataQuery' : IDL.Func([IDL.Nat], [IDL.Opt(LandData)], ['query']),
  'getLandOwner' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Principal)], ['query']),
  'getMyLootCaches' : IDL.Func([], [IDL.Vec(LootCache)], ['query']),
  'getMyModifications' : IDL.Func([], [IDL.Vec(ModifierInstance)], ['query']),
  'getTopLands' : IDL.Func([IDL.Nat], [IDL.Vec(TopLandEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'mintLand' : IDL.Func([], [LandData], []),
  'processCache' : IDL.Func([IDL.Nat], [Result_1], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setGovernanceCanister' : IDL.Func([IDL.Principal], [], []),
  'setMarketplaceCanister' : IDL.Func([IDL.Principal], [], []),
  'setTokenCanister' : IDL.Func([IDL.Principal], [], []),
  'transferLand' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateDecoration' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [Result], []),
  'updatePlotName' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'upgradePlot' : IDL.Func([IDL.Nat, IDL.Nat], [UpgradeResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Coordinates = IDL.Record({ 'lat' : IDL.Float64, 'lon' : IDL.Float64 });
  const ModifierInstance = IDL.Record({
    'modifierInstanceId' : IDL.Nat,
    'modifierType' : IDL.Text,
    'model_url' : IDL.Text,
    'rarity_tier' : IDL.Nat,
    'multiplier_value' : IDL.Float64,
  });
  const LandData = IDL.Record({
    'decorationURL' : IDL.Opt(IDL.Text),
    'baseTokenMultiplier' : IDL.Float64,
    'lastChargeUpdate' : Time,
    'upgradeLevel' : IDL.Nat,
    'principal' : IDL.Principal,
    'landId' : IDL.Nat,
    'lastClaimTime' : Time,
    'biome' : IDL.Text,
    'chargeCap' : IDL.Nat,
    'cycleCharge' : IDL.Int,
    'plotName' : IDL.Text,
    'coordinates' : Coordinates,
    'attachedModifications' : IDL.Vec(ModifierInstance),
  });
  const Modifier = IDL.Record({
    'name' : IDL.Text,
    'asset_url' : IDL.Text,
    'mod_id' : IDL.Nat,
    'rarity_tier' : IDL.Nat,
    'multiplier_value' : IDL.Float64,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : LandData, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClaimResult = IDL.Variant({
    'success' : IDL.Record({
      'tokensClaimed' : IDL.Nat,
      'newBalance' : IDL.Nat,
      'nextClaimTime' : IDL.Int,
    }),
    'mintFailed' : IDL.Text,
    'cooldown' : IDL.Record({
      'currentBalance' : IDL.Nat,
      'remainingTime' : IDL.Int,
    }),
    'insufficientCharge' : IDL.Record({
      'required' : IDL.Nat,
      'current' : IDL.Int,
    }),
  });
  const LootCache = IDL.Record({
    'owner' : IDL.Principal,
    'tier' : IDL.Nat,
    'cache_id' : IDL.Nat,
    'discovered_at' : Time,
    'is_opened' : IDL.Bool,
  });
  const Result_3 = IDL.Variant({ 'ok' : LootCache, 'err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TopLandEntry = IDL.Record({
    'upgradeLevel' : IDL.Nat,
    'principal' : IDL.Principal,
    'tokenBalance' : IDL.Nat,
    'plotName' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : ModifierInstance, 'err' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpgradeResult = IDL.Variant({
    'maxLevelReached' : IDL.Null,
    'success' : IDL.Record({
      'newLevel' : IDL.Nat,
      'remainingTokens' : IDL.Nat,
    }),
    'insufficientTokens' : IDL.Record({
      'required' : IDL.Nat,
      'current' : IDL.Nat,
    }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetLandData' : IDL.Func([IDL.Nat], [IDL.Opt(LandData)], []),
    'adminSetAllModifiers' : IDL.Func([IDL.Vec(Modifier)], [Result], []),
    'applyModifier' : IDL.Func([IDL.Nat, IDL.Nat], [Result_4], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimRewards' : IDL.Func([IDL.Nat], [ClaimResult], []),
    'discoverLootCache' : IDL.Func([IDL.Nat], [Result_3], []),
    'getAllModifiers' : IDL.Func([], [IDL.Vec(Modifier)], ['query']),
    'getAssetCanisterCycleBalance' : IDL.Func([], [Result_2], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentCbrBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getLandData' : IDL.Func([], [IDL.Vec(LandData)], []),
    'getLandDataQuery' : IDL.Func([IDL.Nat], [IDL.Opt(LandData)], ['query']),
    'getLandOwner' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Principal)], ['query']),
    'getMyLootCaches' : IDL.Func([], [IDL.Vec(LootCache)], ['query']),
    'getMyModifications' : IDL.Func([], [IDL.Vec(ModifierInstance)], ['query']),
    'getTopLands' : IDL.Func([IDL.Nat], [IDL.Vec(TopLandEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'mintLand' : IDL.Func([], [LandData], []),
    'processCache' : IDL.Func([IDL.Nat], [Result_1], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setGovernanceCanister' : IDL.Func([IDL.Principal], [], []),
    'setMarketplaceCanister' : IDL.Func([IDL.Principal], [], []),
    'setTokenCanister' : IDL.Func([IDL.Principal], [], []),
    'transferLand' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateDecoration' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [Result], []),
    'updatePlotName' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'upgradePlot' : IDL.Func([IDL.Nat, IDL.Nat], [UpgradeResult], []),
  });
};

export const init = ({ IDL }) => { return []; };