/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClaimResult = { 'Ok' : number } |
  { 'Err' : string };
export interface LandData {
  'lat' : number,
  'lon' : number,
  'decorationURL' : [] | [string],
  'baseTokenMultiplier' : number,
  'lastChargeUpdate' : Time,
  'upgradeLevel' : bigint,
  'owner' : Principal,
  'landId' : bigint,
  'lastClaimTime' : Time,
  'biome' : string,
  'chargeCap' : bigint,
  'cycleCharge' : bigint,
  'plotName' : string,
  'attachedModifications' : Array<ModifierInstance>,
}
export interface LootCache {
  'owner' : Principal,
  'tier' : bigint,
  'cache_id' : bigint,
  'discovered_at' : Time,
  'is_opened' : boolean,
}
export interface Modifier {
  'name' : string,
  'asset_url' : string,
  'mod_id' : bigint,
  'rarity_tier' : bigint,
  'multiplier_value' : number,
}
export interface ModifierInstance {
  'modifierInstanceId' : bigint,
  'modifierType' : string,
  'model_url' : string,
  'rarity_tier' : bigint,
  'multiplier_value' : number,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : ModifierInstance } |
  { 'err' : string };
export type Result_2 = { 'ok' : LandData } |
  { 'err' : string };
export type Result_3 = { 'ok' : string } |
  { 'err' : string };
export type Result_4 = { 'ok' : LootCache } |
  { 'err' : string };
export type Time = bigint;
export interface TopLandEntry {
  'upgradeLevel' : bigint,
  'owner' : Principal,
  'landId' : bigint,
  'tokenBalance' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UpgradeResult = { 'Ok' : LandData } |
  { 'Err' : string };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetLandData' : ActorMethod<[bigint], [] | [LandData]>,
  'adminSetAllModifiers' : ActorMethod<[Array<Modifier>], Result>,
  'applyModifier' : ActorMethod<[bigint, bigint], Result_2>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimRewards' : ActorMethod<[bigint], ClaimResult>,
  'discoverLootCache' : ActorMethod<[bigint], Result_4>,
  'getAllModifiers' : ActorMethod<[], Array<Modifier>>,
  'getAssetCanisterCycleBalance' : ActorMethod<[], Result_3>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentCbrBalance' : ActorMethod<[], number>,
  'getLandData' : ActorMethod<[bigint], [] | [LandData]>,
  'getLandDataQuery' : ActorMethod<[bigint], [] | [LandData]>,
  'getLandOwner' : ActorMethod<[bigint], [] | [Principal]>,
  'getMyLootCaches' : ActorMethod<[], Array<LootCache>>,
  'getMyModifications' : ActorMethod<[], Array<ModifierInstance>>,
  'getTopLands' : ActorMethod<[bigint], Array<TopLandEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mintLand' : ActorMethod<[], Result_2>,
  'processCache' : ActorMethod<[bigint], Result_1>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setGovernanceCanister' : ActorMethod<[Principal], undefined>,
  'setMarketplaceCanister' : ActorMethod<[Principal], undefined>,
  'setTokenCanister' : ActorMethod<[Principal], undefined>,
  'transferLand' : ActorMethod<[bigint, Principal], Result>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDecoration' : ActorMethod<[bigint, [] | [string]], Result>,
  'updatePlotName' : ActorMethod<[bigint, string], Result>,
  'upgradePlot' : ActorMethod<[bigint], UpgradeResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];