/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Result_2 = {
    __kind__: "ok";
    ok: LandData;
} | {
    __kind__: "err";
    err: string;
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface LootCache {
    owner: Principal;
    tier: bigint;
    cache_id: bigint;
    discovered_at: Time;
    is_opened: boolean;
}
export type ClaimResult = {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
};
export interface LandData {
    lat: number;
    lon: number;
    decorationURL?: string;
    baseTokenMultiplier: number;
    lastChargeUpdate: Time;
    upgradeLevel: bigint;
    owner: Principal;
    landId: bigint;
    lastClaimTime: Time;
    biome: string;
    chargeCap: bigint;
    cycleCharge: bigint;
    plotName: string;
    attachedModifications: Array<ModifierInstance>;
}
export type Result_1 = {
    __kind__: "ok";
    ok: ModifierInstance;
} | {
    __kind__: "err";
    err: string;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Result_4 = {
    __kind__: "ok";
    ok: LootCache;
} | {
    __kind__: "err";
    err: string;
};
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface TopLandEntry {
    upgradeLevel: bigint;
    owner: Principal;
    landId: bigint;
    tokenBalance: number;
}
export type Result_3 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Modifier {
    name: string;
    asset_url: string;
    mod_id: bigint;
    rarity_tier: bigint;
    multiplier_value: number;
}
export type UpgradeResult = {
    __kind__: "Ok";
    Ok: LandData;
} | {
    __kind__: "Err";
    Err: string;
};
export interface ModifierInstance {
    modifierInstanceId: bigint;
    modifierType: string;
    model_url: string;
    rarity_tier: bigint;
    multiplier_value: number;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminGetLandData(landId: bigint): Promise<LandData | null>;
    adminSetAllModifiers(mods: Array<Modifier>): Promise<Result>;
    applyModifier(landId: bigint, modifierInstanceId: bigint): Promise<Result_2>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimRewards(landId: bigint): Promise<ClaimResult>;
    discoverLootCache(tier: bigint): Promise<Result_4>;
    getAllModifiers(): Promise<Array<Modifier>>;
    getAssetCanisterCycleBalance(): Promise<Result_3>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentCbrBalance(): Promise<number>;
    getLandData(landId: bigint): Promise<LandData | null>;
    getLandDataQuery(landId: bigint): Promise<LandData | null>;
    getLandOwner(landId: bigint): Promise<Principal | null>;
    getMyLootCaches(): Promise<Array<LootCache>>;
    getMyModifications(): Promise<Array<ModifierInstance>>;
    getTopLands(n: bigint): Promise<Array<TopLandEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    mintLand(): Promise<Result_2>;
    processCache(cache_id: bigint): Promise<Result_1>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setGovernanceCanister(p: Principal): Promise<void>;
    setMarketplaceCanister(p: Principal): Promise<void>;
    setTokenCanister(p: Principal): Promise<void>;
    transferLand(landId: bigint, to: Principal): Promise<Result>;
    transform(raw: TransformationInput): Promise<TransformationOutput>;
    updateDecoration(landId: bigint, url: string | null): Promise<Result>;
    updatePlotName(landId: bigint, name: string): Promise<Result>;
    upgradePlot(landId: bigint): Promise<UpgradeResult>;
}
import type { ClaimResult as _ClaimResult, LandData as _LandData, LootCache as _LootCache, ModifierInstance as _ModifierInstance, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Time as _Time, UpgradeResult as _UpgradeResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminGetLandData(arg0: bigint): Promise<LandData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetLandData(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetLandData(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSetAllModifiers(arg0: Array<Modifier>): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetAllModifiers(arg0);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetAllModifiers(arg0);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async applyModifier(arg0: bigint, arg1: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.applyModifier(arg0, arg1);
                return from_candid_Result_2_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyModifier(arg0, arg1);
            return from_candid_Result_2_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimRewards(arg0: bigint): Promise<ClaimResult> {
        if (this.processError) {
            try {
                const result = await this.actor.claimRewards(arg0);
                return from_candid_ClaimResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimRewards(arg0);
            return from_candid_ClaimResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async discoverLootCache(arg0: bigint): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.discoverLootCache(arg0);
                return from_candid_Result_4_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.discoverLootCache(arg0);
            return from_candid_Result_4_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllModifiers(): Promise<Array<Modifier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllModifiers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllModifiers();
            return result;
        }
    }
    async getAssetCanisterCycleBalance(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetCanisterCycleBalance();
                return from_candid_Result_3_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetCanisterCycleBalance();
            return from_candid_Result_3_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentCbrBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentCbrBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentCbrBalance();
            return result;
        }
    }
    async getLandData(arg0: bigint): Promise<LandData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandData(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandData(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLandDataQuery(arg0: bigint): Promise<LandData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandDataQuery(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandDataQuery(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLandOwner(arg0: bigint): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandOwner(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandOwner(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLootCaches(): Promise<Array<LootCache>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLootCaches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLootCaches();
            return result;
        }
    }
    async getMyModifications(): Promise<Array<ModifierInstance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyModifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyModifications();
            return result;
        }
    }
    async getTopLands(arg0: bigint): Promise<Array<TopLandEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopLands(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopLands(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async mintLand(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.mintLand();
                return from_candid_Result_2_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintLand();
            return from_candid_Result_2_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async processCache(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.processCache(arg0);
                return from_candid_Result_1_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processCache(arg0);
            return from_candid_Result_1_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setGovernanceCanister(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGovernanceCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGovernanceCanister(arg0);
            return result;
        }
    }
    async setMarketplaceCanister(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMarketplaceCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMarketplaceCanister(arg0);
            return result;
        }
    }
    async setTokenCanister(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTokenCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTokenCanister(arg0);
            return result;
        }
    }
    async transferLand(arg0: bigint, arg1: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.transferLand(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferLand(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateDecoration(arg0: bigint, arg1: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDecoration(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDecoration(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePlotName(arg0: bigint, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlotName(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlotName(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async upgradePlot(arg0: bigint): Promise<UpgradeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradePlot(arg0);
                return from_candid_UpgradeResult_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradePlot(arg0);
            return from_candid_UpgradeResult_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ClaimResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClaimResult): ClaimResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_LandData_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LandData): LandData {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UpgradeResult_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpgradeResult): UpgradeResult {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LandData]): LandData | null {
    return value.length === 0 ? null : from_candid_LandData_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lon: number;
    decorationURL: [] | [string];
    baseTokenMultiplier: number;
    lastChargeUpdate: _Time;
    upgradeLevel: bigint;
    owner: Principal;
    landId: bigint;
    lastClaimTime: _Time;
    biome: string;
    chargeCap: bigint;
    cycleCharge: bigint;
    plotName: string;
    attachedModifications: Array<_ModifierInstance>;
}): {
    lat: number;
    lon: number;
    decorationURL?: string;
    baseTokenMultiplier: number;
    lastChargeUpdate: Time;
    upgradeLevel: bigint;
    owner: Principal;
    landId: bigint;
    lastClaimTime: Time;
    biome: string;
    chargeCap: bigint;
    cycleCharge: bigint;
    plotName: string;
    attachedModifications: Array<ModifierInstance>;
} {
    return {
        lat: value.lat,
        lon: value.lon,
        decorationURL: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.decorationURL)),
        baseTokenMultiplier: value.baseTokenMultiplier,
        lastChargeUpdate: value.lastChargeUpdate,
        upgradeLevel: value.upgradeLevel,
        owner: value.owner,
        landId: value.landId,
        lastClaimTime: value.lastClaimTime,
        biome: value.biome,
        chargeCap: value.chargeCap,
        cycleCharge: value.cycleCharge,
        plotName: value.plotName,
        attachedModifications: value.attachedModifications
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: number;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LootCache;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LootCache;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ModifierInstance;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ModifierInstance;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: _LandData;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: LandData;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_LandData_n2(_uploadFile, _downloadFile, value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LandData;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LandData;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_LandData_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
